// Renders the AGREED order form as a self-contained HTML document that gets filed
// in Salesforce (ContentVersion) when a customer accepts. Mirrors the live offer page
// but stamped "ACCEPTED" — this is the artifact a rep opens on the Quote/Opportunity.
const money = (n: number) => "$" + Number(n || 0).toLocaleString("en-US", { maximumFractionDigits: 0 });

export function renderAgreedOrderForm(opts: { account: string; quote: any; acceptedOn?: string }): string {
  const q = opts.quote;
  const lines = (q.QuoteLineItems?.records || []) as any[];
  const acceptedOn = opts.acceptedOn || new Date().toISOString().slice(0, 10);
  const rows = lines
    .map((li) => {
      const disc = Number(li.Discount || 0);
      const free = disc >= 100 || Number(li.TotalPrice) === 0;
      const amount = free ? `<span style="color:#059669;font-weight:800">$0</span> <span style="color:#059669;font-size:11px">(100% waived)</span>` : money(li.TotalPrice);
      return `<tr>
        <td style="padding:10px 8px;border-bottom:1px solid #eef1f6;font-family:ui-monospace,Menlo,monospace;font-size:12px;color:#334">${li.Product2?.ProductCode || ""}</td>
        <td style="padding:10px 8px;border-bottom:1px solid #eef1f6">${li.Product2?.Name || ""}</td>
        <td style="padding:10px 8px;border-bottom:1px solid #eef1f6;text-align:right">${li.Quantity}</td>
        <td style="padding:10px 8px;border-bottom:1px solid #eef1f6;text-align:right">${money(li.UnitPrice)}${disc > 0 && !free ? ` <span style="color:#b45309;font-size:11px">−${disc}%</span>` : ""}</td>
        <td style="padding:10px 8px;border-bottom:1px solid #eef1f6;text-align:right;font-weight:700">${amount}</td>
      </tr>`;
    })
    .join("");
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"/>
<title>Agreed Order Form — ${q.Name}</title></head>
<body style="margin:0;font-family:ui-sans-serif,-apple-system,'Segoe UI',Roboto,Helvetica,sans-serif;color:#0f1729;background:#fff">
<div style="max-width:760px;margin:0 auto;padding:32px">
  <div style="display:flex;justify-content:space-between;align-items:flex-start;border-bottom:2px solid #0b1f3a;padding-bottom:16px">
    <div>
      <div style="letter-spacing:.18em;text-transform:uppercase;font-size:11px;color:#5b6b85;font-weight:700">Order Form</div>
      <h1 style="margin:6px 0 2px;font-size:24px">${opts.account}</h1>
      <div style="color:#5b6b85;font-size:14px">${q.Name}</div>
    </div>
    <div style="text-align:right">
      <div style="display:inline-block;background:#ecfdf5;border:1px solid #6ee7b7;color:#047857;font-weight:800;padding:6px 12px;border-radius:8px;font-size:13px">✓ ACCEPTED</div>
      <div style="color:#5b6b85;font-size:12px;margin-top:6px">Agreed ${acceptedOn}</div>
    </div>
  </div>
  <table style="width:100%;border-collapse:collapse;margin-top:18px;font-size:14px">
    <thead><tr style="color:#5b6b85;font-size:11px;text-transform:uppercase;letter-spacing:.04em">
      <th style="text-align:left;padding:8px">SKU</th><th style="text-align:left;padding:8px">Item</th>
      <th style="text-align:right;padding:8px">Qty</th><th style="text-align:right;padding:8px">Unit</th><th style="text-align:right;padding:8px">Amount</th>
    </tr></thead>
    <tbody>${rows}</tbody>
    <tfoot><tr><td colspan="4" style="text-align:right;padding:14px 8px;font-weight:700;border-top:2px solid #0b1f3a">Annual total</td>
      <td style="text-align:right;padding:14px 8px;font-weight:800;font-size:18px;border-top:2px solid #0b1f3a">${money(q.TotalPrice)}</td></tr></tfoot>
  </table>
  <div style="margin-top:18px;background:#ecfdf5;border:1px solid #a7f3d0;color:#065f46;border-radius:10px;padding:14px 16px;font-size:13.5px;line-height:1.5">
    Platform <b>seats are included (100% waived)</b>; the customer commits to the annual <b>usage pool</b>, expanded with dedicated engineering and premium support. Generated by Sales Factory and filed to Salesforce on acceptance.
  </div>
  <div style="margin-top:24px;color:#8a98ad;font-size:12px;border-top:1px solid #e4e9f2;padding-top:12px">Quote ${q.Id} · accepted by customer · ${acceptedOn}</div>
</div></body></html>`;
}
